// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
// Deliberately no `migrations.seed` here — docker-compose.demo-orderflow.yml
// runs prisma/seed.mjs directly (`node prisma/seed.mjs`), not via
// `prisma db seed`, after a real ts-node/generated-Prisma-client
// incompatibility hit going that route (see seed.mjs's own header
// comment).
